name: 'Hi'

on:
  push:
    branches: 
      - 'master'
  pull_request: 
    branches: 
      - 'master'
  
jobs:
  test: 
    runs-on: ubuntu-lates
    steps:
      -uses: actions/checkout@v2
      -uses: ./